### ISSUE TITLE
fix labels in temoa_processing notebook

### ISSUE THREAD

**Issue by robfairh** [arfc/pride#83] opened 2020-07-22 15:51 UTC
Currently, the figures in [this](https://github.com/arfc/pride/blob/master/temoa-uiuc/temoa_processing.ipynb) notebook look like this:

![image](https://user-images.githubusercontent.com/43791150/88198229-1e19ca00-cc09-11ea-9f91-cd4626c01158.png)

This issue can be closed when a PR fixes the labels.
Some possibilities are making the bars wider or rotating the labels slightly.

**Comment by samgdotson** [comment] 2020-07-22 16:00
This issue is a duplicate of #84 (@robfairh and I created these issues simultaneously). 

Closing

**Closed as completed by samgdotson** 2020-07-22 16:00 UTC
Labels: Comp:Analysis, Difficulty:1-Beginner, Status:1-New, Status:6-Duplicate, Type:Style
